### ISSUE TITLE
spring boot plugin version should be `springBootVersion = '1.5.10.RELEASE`

### ISSUE THREAD

**Issue by shartoo** [florind/inception-serving-sb#2]
The spring boot plugin should be `springBootVersion = '1.5.10.RELEASE` (this is the latest version till Jan 31)

**Comment by florind** [comment]
This project is not based on the latest stable Spring Boot (currently 1.5.x) but on the upcoming 2.0.

**Comment by shartoo** [comment]
All right,thank you!
